# Permalinks
permalink:           pretty

# Setup
title:               Krerkkiat Chusap
url:                 http://getpoole.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Krerkkiat Chusap
  url:               https://twitter.com/krerkkiat_c

# Custom vars

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
